-- 025_product_article_images_theme_driven_pipeline.sql
--
-- No schema change (same as 024) -- this migration only corrects
-- product_articles' image-column comments again, which still described
-- 024's cutout+generated-background+composite pipeline. That pipeline
-- is being abandoned after Al reviewed real reference examples (a
-- bowling.com-style multi-colorway lane shot, and a separate "Fallout"
-- ball with a post-apocalyptic wasteland backdrop clearly themed off
-- the ball's own name) and gave three pieces of direct feedback:
--   1. the action shot still didn't look like real editorial bowling
--      photography,
--   2. backgrounds should be driven by the PRODUCT'S OWN NAME/BRANDING
--      (a "Fallout" ball should evoke a wasteland, not a generic lane),
--      not a generic bowling-lane/studio backdrop,
--   3. verbatim: "I think we are trying to be to technical on this
--      maybe there is a better ai model for this" -- and, asked
--      directly whether pixel-perfect ball preservation could be traded
--      for visual quality via a simpler approach: yes.
--
-- 024's whole raison d'etre was guaranteeing "we can not alter the ball
-- in any way" via a three-step pipeline (segment the ball out via
-- Bedrock's Remove Background model, generate a background separately,
-- composite with Pillow). With Al now explicitly OK trading that
-- guarantee for quality and simplicity, that pipeline's entire reason to
-- exist is gone -- so this reverts to a SINGLE Stable Diffusion 3.5
-- Large image-to-image call per variant (the same model this project
-- already uses, same mechanism 023 originally shipped), which is both
-- simpler (one Bedrock call instead of three, one Region instead of
-- three, no separate Remove Background Marketplace subscription/IAM
-- grant -- see the GrantRemoveBgModelAccess saga this migration also
-- retires in template.yaml) and, per Al's own reference examples,
-- produces more cohesive, higher-quality output than compositing two
-- separately-generated pieces together.
--
-- What's actually NEW relative to 023's original img2img mechanism (not
-- just a revert): the image prompt is now grounded in a THEME the text
-- model itself derives from the product's own name/branding (see
-- build_article_prompt's new optional visual_theme ask in app.py) --
-- Al's explicit "background driven by the ball's name" ask -- rather
-- than 023's generic "editorial action photograph of {color} bowling
-- ball" description. Aspect ratio (still 16:9 action / 1:1 product, per
-- Al's earlier answer) is now achieved by LETTERBOXING the real
-- reference photo onto a canvas of the target aspect ratio before the
-- img2img call, since Stable Diffusion's aspect_ratio parameter is
-- text-to-image-only and image-to-image mode instead preserves whatever
-- aspect ratio the INPUT image already has.

begin;

comment on column product_articles.action_shot_image_key is 'S3 key (IMAGE_BUCKET, article-images/ prefix) for the action/lifestyle hero shot -- a 16:9 image generated by Stable Diffusion 3.5 Large image-to-image, conditioned on the product''s real reference photo letterboxed onto a 16:9 canvas (build_reference_canvas), with a prompt grounded in a visual theme the article-generation model itself derived from the product''s own name/branding (build_image_prompts). Ball fidelity is best-effort, not guaranteed pixel-identical -- see this migration''s own header comment for why that tradeoff was made. Null if image generation has not yet succeeded for this row.';
comment on column product_articles.product_shot_image_key is 'S3 key (IMAGE_BUCKET, article-images/ prefix) for the stylized product hero shot -- same theme-driven image-to-image mechanism as action_shot_image_key, but at a 1:1 aspect ratio and an elevated studio-backdrop prompt instead of a bowling-lane one. Null if image generation has not yet succeeded for this row.';
comment on column product_articles.images_generated_at is 'Set once the image-generation step runs and produces AT LEAST ONE of the two images -- not gated on both succeeding, since the two Stable Diffusion image-to-image calls (one per variant) fail independently. Check action_shot_image_key/product_shot_image_key individually (either may still be null) to see which one actually succeeded.';

commit;
