"""
Pushes our approved, summarized YouTube videos into BigCommerce's own
native Product Videos feature on bowlerdepot.com -- Al's ask: "for the
public side of things what is the best way to include a section
containing the data from this project on our bigcommerce product pages...
pull in the video section into the video section of the bigcommerce
product page."

Investigated live (Claude in Chrome) against a real BowlerDepot product
page, bowlerdepot.com/brunswick-combat-solid/, before writing any of this:
the storefront theme (Supermarket) already has a native "Videos" tab
(#tab-videos > .videoGallery--inTab) driven entirely by BigCommerce's own
built-in Product Videos feature -- already populated with a manufacturer
video for that product. BigCommerce's own v3 Catalog API
(POST /catalog/products/{id}/videos, confirmed via their live docs --
required field video_id, optional title/description/sort_order/type)
writes directly into that same native slot, which the theme already knows
how to render. So the right integration here is a small SERVER-SIDE sync
that pushes videos into BigCommerce's own feature, not a client-side
widget trying to reconstruct a video player/gallery from scratch --
that's a fundamentally different (and much smaller, much more robust)
piece of work than the separate video_reviews_summary embed script this
same conversation also produced (see public_api's new /bowlerdepot/
products/{bigcommerce_product_id}/video-summary route + the standalone
embed script for that piece -- this module only handles the per-video
push, not the aggregate rollup summary, since BigCommerce's Product Video
model has no field for an aggregate paragraph, only a per-video
description).

Each video's `description` in BigCommerce IS populated with our own
product_videos.summary (the per-video AI summary already generated by
video_summarizer) -- that comes along for free as part of this same push,
no separate script needed for it, unlike the aggregate rollup.

Matching: reuses bowlerdepot_products (Al's existing BigCommerce
reconciliation table, product_id -> bigcommerce_product_id) rather than
building new matching logic -- only pushes videos for a product with
match_status='matched' (bowlerdepot_reconciliation's own fuzzy-match
confidence gate; an 'ambiguous'/'unmatched' row is a known-unreliable
match by that module's own design, and this sync must not risk writing a
video onto the WRONG BigCommerce product).

Idempotency: migration 020 added product_videos.bowlerdepot_video_id/
bowlerdepot_synced_at specifically so a re-run of this job only ever
pushes a video once -- "needs sync" is simply bowlerdepot_synced_at is
null, same convention as product_price_sources.last_checked_at elsewhere
in this codebase.

Prerequisite Al needs to confirm/set up himself (not something this code
can verify or fix): the BigCommerce API token behind BIGCOMMERCE_SECRET_ARN
was created for price_checker/bowlerdepot_reconciliation's read-only price
lookups. Per BigCommerce's own docs, writing a Product Video needs the
Products "modify" OAuth scope (store_v2_products), not just the
read-only one (store_v2_products_read_only) those other two functions get
by with. If the existing token is read-only, this function's POST calls
will 403 -- see get_bigcommerce_credentials' docstring.
"""
import json
import logging
import os

logger = logging.getLogger()
logger.setLevel(logging.INFO)

BIGCOMMERCE_API_BASE = "https://api.bigcommerce.com"
DEFAULT_FETCH_TIMEOUT_SECONDS = 30

# BigCommerce's documented limits (Create Product Video docs): title is
# 0-255 chars, video_id is 0-25 chars. A real YouTube video id is always
# 11 chars, comfortably under 25, but title is free text from whatever
# the source video's own title was (see product_videos.title, sourced
# from the YouTube Data API in video_discovery) -- truncated defensively
# rather than letting a long title 400 the whole push.
MAX_TITLE_LENGTH = 255


def get_bigcommerce_credentials():
    """Identical to price_checker.get_bigcommerce_credentials/
    bowlerdepot_reconciliation.get_bigcommerce_credentials -- duplicated,
    not imported/shared, same "each Lambda owns its own deploy package"
    reasoning used throughout this codebase (see product_scraper/app.py's
    publish_messages docstring for the canonical statement of that
    convention).

    Unlike those two callers, THIS function's caller needs the token to
    have the Products "modify" OAuth scope (store_v2_products), not just
    read-only -- BigCommerce's Catalog API rejects a POST with a
    read-only token. Whether the configured secret's token actually has
    that scope isn't something this function (or anything in this
    sandbox) can verify -- Al needs to confirm/upgrade it in BigCommerce's
    own API Accounts settings before this function's pushes will succeed;
    a 403 from push_video_to_bigcommerce is the symptom if it doesn't."""
    import boto3

    secret_arn = os.environ["BIGCOMMERCE_SECRET_ARN"]
    client = boto3.client("secretsmanager")
    secret = json.loads(client.get_secret_value(SecretId=secret_arn)["SecretString"])
    return secret["store_hash"], secret["auth_token"]


def get_db_connection():
    import boto3
    import psycopg2

    secret_arn = os.environ["DB_SECRET_ARN"]
    client = boto3.client("secretsmanager")
    secret = json.loads(client.get_secret_value(SecretId=secret_arn)["SecretString"])

    return psycopg2.connect(
        host=secret["host"],
        port=secret.get("port", 5432),
        dbname=secret["dbname"],
        user=secret["username"],
        password=secret["password"],
    )


def list_videos_needing_sync(conn) -> list:
    """Every approved, summarized video for a product BigCommerce
    reconciliation confidently matched (match_status='matched' -- see
    this module's docstring for why 'ambiguous'/'unmatched' are excluded)
    that hasn't been pushed to BigCommerce yet (bowlerdepot_synced_at is
    null). Same "approved AND summary is not null" bar public_api.
    get_product's own video select already uses for what's public-ready
    -- this sync should never push a video the public site itself
    wouldn't show.

    already_synced_count (a correlated count of this product's
    already-synced videos) seeds the per-product sort_order counter the
    handler keeps as it works through the batch -- computed once here
    rather than re-queried after every push, since a single run's pushes
    haven't landed in the DB yet to recount against."""
    with conn.cursor() as cur:
        cur.execute(
            """
            select pv.id as video_id, pv.product_id, bp.bigcommerce_product_id,
                   pv.youtube_video_id, pv.title, pv.summary,
                   coalesce((
                       select count(*) from product_videos pv2
                       where pv2.product_id = pv.product_id
                         and pv2.bowlerdepot_synced_at is not null
                   ), 0) as already_synced_count
            from product_videos pv
            join bowlerdepot_products bp on bp.product_id = pv.product_id
            join products p on p.id = pv.product_id
            where pv.status = 'approved'
              and pv.summary is not null
              and pv.bowlerdepot_synced_at is null
              and bp.match_status = 'matched'
              and p.published = true
            order by pv.product_id, pv.published_at desc nulls last, pv.id
            """
        )
        columns = [desc[0] for desc in cur.description]
        return [dict(zip(columns, row)) for row in cur.fetchall()]


def build_bigcommerce_video_payload(video: dict, sort_order: int) -> dict:
    """Pure function -- maps one of our product_videos rows to the exact
    request body BigCommerce's Create Product Video endpoint documents
    (confirmed live via their own docs page this session):
    {title, description, sort_order, type, video_id}. description is our
    own per-video AI summary (video.summary) -- this is what gets the
    summary onto the storefront "for free" as part of the native video
    push, distinct from the separate aggregate-rollup embed script (see
    module docstring)."""
    title = (video.get("title") or "")[:MAX_TITLE_LENGTH]
    return {
        "title": title,
        "description": video.get("summary") or "",
        "sort_order": sort_order,
        "type": "youtube",
        "video_id": video["youtube_video_id"],
    }


def push_video_to_bigcommerce(session, store_hash: str, auth_token: str,
                               bigcommerce_product_id: str, payload: dict) -> dict:
    """POSTs one video, returns the created video object (the response's
    "data" key -- has BigCommerce's own new id, which the caller stores
    as bowlerdepot_video_id). Raises on a non-2xx response (resp.
    raise_for_status()) -- caller (_process_one_video) is what catches
    that per-video, so one bad push doesn't abort the whole batch."""
    resp = session.post(
        f"{BIGCOMMERCE_API_BASE}/stores/{store_hash}/v3/catalog/products/{bigcommerce_product_id}/videos",
        headers={
            "Accept": "application/json",
            "Content-Type": "application/json",
            "X-Auth-Token": auth_token,
        },
        json=payload,
        timeout=DEFAULT_FETCH_TIMEOUT_SECONDS,
    )
    resp.raise_for_status()
    return resp.json()["data"]


def mark_video_synced(conn, video_id: str, bigcommerce_video_id) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            update product_videos
            set bowlerdepot_video_id = %s, bowlerdepot_synced_at = now()
            where id = %s
            """,
            (str(bigcommerce_video_id), video_id),
        )
    conn.commit()


def _process_one_video(session, conn, store_hash: str, auth_token: str,
                        video: dict, sort_order: int) -> dict:
    """Pushes one video and records the result -- exceptions are caught
    HERE (not left to propagate) so handler's loop can keep going through
    the rest of the batch after one product's push fails (e.g. a stale
    bigcommerce_product_id, or the 403-from-read-only-token case this
    module's docstring flags as a real, plausible first-run outcome)."""
    try:
        payload = build_bigcommerce_video_payload(video, sort_order)
        created = push_video_to_bigcommerce(
            session, store_hash, auth_token, video["bigcommerce_product_id"], payload,
        )
        mark_video_synced(conn, video["video_id"], created["id"])
        return {"video_id": str(video["video_id"]), "success": True}
    except Exception as exc:
        logger.exception(
            "Failed to push video %s (product %s, bigcommerce_product_id %s) to BigCommerce",
            video.get("video_id"), video.get("product_id"), video.get("bigcommerce_product_id"),
        )
        return {"video_id": str(video.get("video_id")), "success": False, "error": str(exc)}


def handler(event, context):
    """Scheduled, batch-style job (no SQS/per-message shape needed --
    see template.yaml's DailySchedule on this function): processes every
    currently-due video in one invocation, same "run once, do everything
    outstanding" shape as UrlDiscoveryFunction rather than a queue-driven
    fan-out, since the expected volume (approved videos catalog-wide) is
    small relative to Lambda's timeout."""
    import requests

    conn = get_db_connection()
    try:
        videos = list_videos_needing_sync(conn)
        if not videos:
            logger.info("No videos need syncing to BigCommerce")
            return {"statusCode": 200, "body": json.dumps({"pushed": 0, "failed": 0, "results": []})}

        store_hash, auth_token = get_bigcommerce_credentials()
        session = requests.Session()

        # Per-product running sort_order counter, seeded from each row's
        # own already_synced_count (see list_videos_needing_sync's
        # docstring) -- incremented only after a successful push for that
        # product, so a failed push doesn't waste/skip a sort_order slot
        # for the next real success.
        next_sort_order_by_product = {}
        results = []
        for video in videos:
            product_id = video["product_id"]
            if product_id not in next_sort_order_by_product:
                next_sort_order_by_product[product_id] = video["already_synced_count"]
            sort_order = next_sort_order_by_product[product_id]

            result = _process_one_video(session, conn, store_hash, auth_token, video, sort_order)
            results.append(result)
            if result["success"]:
                next_sort_order_by_product[product_id] += 1

        pushed = sum(1 for r in results if r["success"])
        failed = len(results) - pushed
        logger.info("BigCommerce video sync: %d pushed, %d failed", pushed, failed)
        return {"statusCode": 200, "body": json.dumps({"pushed": pushed, "failed": failed, "results": results})}
    finally:
        conn.close()
