"""
HTML product scraper for the WooCommerce brand family (SWAG Bowling to
start -- see woocommerce_url_discovery/app.py's module docstring for the
platform confirmation).

Reads WooCommerce's standard "Additional information" attribute table
(generated by WooCommerce core's own product-attributes template, not
site-specific theme markup -- the label text is a WooCommerce/WordPress
taxonomy convention, stable across WooCommerce sites generally, not just
this one). Confirmed real against swagbowling.com/product/swag-fusion-
bowling-ball/ this session -- every label in ATTRIBUTE_LABELS and the
values in tests/fixtures/swag_fusion.html's real-data reconstruction come
directly from that live fetch.

Two real, confirmed structural differences from the Craft-CMS scraper
(product_scraper/app.py) that shaped this module's design:

1. SWAG's attribute table only ever gives a single RG/DIFF value, labeled
   "(15LB)" explicitly in the field name -- there is no per-weight
   breakdown table like Brunswick's Core Numbers table. So this always
   takes the 15lb-default path; PARSE_WEIGHT_TABLE doesn't exist here
   because there's nothing to parse a table out of.
2. Coverstock material and type live in different fields than Brunswick:
   "Bowling Ball Coverstock Type" gives the material (Reactive/Urethane/
   Polyester) directly, but Solid/Pearl/Hybrid isn't a separate field --
   it's embedded in "Bowling Ball Cover Name" text (e.g. "SWAG Xplode
   Solid Reactive"), same keyword-matching approach as Brunswick's
   parse_coverstock but applied to a different source field.

Known, disclosed gap: "Mass Bias Strength" was "N/A" on the one real ball
inspected this session (a symmetric core, where that's expected). Whether
SWAG expresses mass bias for asymmetric balls as a real number (like
Brunswick's PDF-sourced ASY values) or as a qualitative label (e.g.
"Strong"/"Moderate") wasn't confirmed -- no real asymmetric SWAG product
page was inspected this session. parse_mass_bias() below only accepts a
numeric value and returns None otherwise, so a qualitative value won't
crash anything, but it also won't be captured anywhere -- verify against
a real asymmetric ball (e.g. one of the "Asymmetric Core" balls seen in
the category listing) before trusting mass bias data from this scraper.

Real finding from this deploy's first live smoke test (all 96 real
products, not just Fusion): roughly a third of SWAG's catalog are
WooCommerce "External/Affiliate Product" listings -- confirmed via the
product-type-external CSS class and a total absence of the
woocommerce-tabs/"Additional information" section (checked against
swag-apex-pearl-bowling-ball's real page). These redirect to a different
retailer rather than being a real SWAG-hosted product page, so there's
no attribute data to scrape at all. This module was only ever built and
verified against Fusion, a regular/simple product -- the external-
product case wasn't something the original research surfaced.
parse_product_page() now returns an {"external_product": True} sentinel
for these instead of a dict with status=None, which used to crash the DB
write on the products.status NOT NULL constraint (and pointlessly retry
3x into the DLQ, since retrying never helps a permanently-external
listing) -- see _process_one()'s handling of that sentinel.
"""
import logging
import re
from datetime import datetime
from urllib.parse import urljoin

from bs4 import BeautifulSoup

logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Real label text confirmed from swagbowling.com/product/swag-fusion-bowling-ball/.
# Matched case-insensitively; majority-match (not all required) since not
# every ball necessarily populates every attribute.
ATTRIBUTE_LABELS = {
    "ball performance level", "production-status", "brand", "colors",
    "bowling ball core name", "bowling ball core shape",
    "bowling ball cover name", "bowling ball coverstock type",
    "radius of gyration: rg (15lb)", "differential: diff (15lb)",
    "mass bias strength", "flare potential", "preferred lane conditions",
    "surface finish", "ball weight", "release date", "suggested retail price",
}

COVERSTOCK_MATERIAL_KEYWORDS = [
    ("urethane", "urethane"),
    ("polyester", "polyester_plastic"),
    ("plastic", "polyester_plastic"),
    ("reactive", "reactive_resin"),
]
COVERSTOCK_TYPE_KEYWORDS = [
    ("solid", "solid"),
    ("pearl", "pearl"),
    ("hybrid", "hybrid"),
]

WEIGHT_TOKEN_RE = re.compile(r"(\d{1,2})\s*lb", re.IGNORECASE)
# Matches "2.54", ".036" (real SWAG value -- no leading zero), and plain
# integers. Differential in particular is commonly written without a
# leading zero in this industry ("Diff (15LB): .036"), so \d+\.\d+ alone
# (which requires a digit before the dot) would silently miss it.
NUMBER_RE = re.compile(r"-?(?:\d+\.?\d*|\.\d+)")


def fetch_page(url: str, timeout: int = 30) -> str:
    import requests

    resp = requests.get(url, headers={"User-Agent": "bowling-scraper/1.0"}, timeout=timeout)
    resp.raise_for_status()
    return resp.text


def _clean(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _find_attributes_table(soup: BeautifulSoup, min_matches: int = 4):
    """Same content-matching approach as product_scraper's
    _find_table_by_row_labels -- majority-match against known labels
    rather than any CSS class, so this survives WooCommerce theme changes
    (the labels are a WooCommerce/WordPress platform convention; the
    class names around them are theme-dependent)."""
    for table in soup.find_all("table"):
        matches = 0
        for row in table.find_all("tr"):
            cells = row.find_all(["th", "td"])
            if not cells:
                continue
            label = _clean(cells[0].get_text()).lower()
            if label in ATTRIBUTE_LABELS:
                matches += 1
        if matches >= min_matches:
            return table
    return None


def parse_attributes_table(table) -> dict:
    attrs = {}
    for row in table.find_all("tr"):
        cells = row.find_all(["th", "td"])
        if len(cells) < 2:
            continue
        label = _clean(cells[0].get_text()).lower()
        value = _clean(cells[1].get_text())
        if label in ATTRIBUTE_LABELS:
            attrs[label] = value
    return attrs


def _to_float(value):
    if not value:
        return None
    match = NUMBER_RE.search(value)
    return float(match.group()) if match else None


def parse_mass_bias(value):
    """Only accepts a literal number. Returns None for "N/A" or any
    qualitative value (e.g. "Strong") rather than guessing a numeric
    mapping -- see module docstring's disclosed gap re: unconfirmed
    asymmetric-ball format."""
    if not value:
        return None
    if not NUMBER_RE.search(value):
        return None
    # Guard against accidentally matching a stray digit inside a word
    # (e.g. a hypothetical "Tier 2" style value) -- require the match to
    # look like an actual numeric value, optionally with a leading dot.
    if re.fullmatch(r"-?(\d+\.?\d*|\.\d+)", value.strip()):
        return float(value.strip())
    return None


def parse_coverstock(coverstock_type_value: str, cover_name_value: str) -> dict:
    """Material comes from "Bowling Ball Coverstock Type" directly; type
    (solid/pearl/hybrid) is inferred from "Bowling Ball Cover Name" text --
    see module docstring for why these are split across two source fields
    here, unlike Brunswick where both come from one "Cover Type" value."""
    material = None
    if coverstock_type_value:
        lowered = coverstock_type_value.lower()
        for keyword, value in COVERSTOCK_MATERIAL_KEYWORDS:
            if keyword in lowered:
                material = value
                break

    cs_type = None
    if cover_name_value:
        lowered = cover_name_value.lower()
        for keyword, value in COVERSTOCK_TYPE_KEYWORDS:
            if keyword in lowered:
                cs_type = value
                break

    return {"coverstock_material": material, "coverstock_type": cs_type}


def parse_release_date(release_date_raw: str):
    """Same "Month YYYY" format as Brunswick's own Release Date field (real
    example: SWAG Fusion's "January 2025", see tests/fixtures/
    swag_fusion.html) -- defaults to the 1st of the month since no day is
    given. Duplicated from product_scraper.parse_release_date rather than
    shared, matching this codebase's established per-module-independent-
    deployment-package convention."""
    if not release_date_raw:
        return None
    cleaned = release_date_raw.strip()
    for fmt in ("%B %Y", "%b %Y"):
        try:
            return datetime.strptime(cleaned, fmt).date()
        except ValueError:
            continue
    return None


def parse_weights_available(ball_weight_value: str):
    """Parses a comma-separated multi-value attribute like
    "13LB, 14LB, 15LB, 16LB" into (low, high) = (13, 16) -- different
    source shape than Brunswick's "16-12 lbs." range string, same
    (low, high) output shape as product_scraper.parse_weights_available."""
    if not ball_weight_value:
        return None
    weights = [int(w) for w in WEIGHT_TOKEN_RE.findall(ball_weight_value)]
    if not weights:
        return None
    return (min(weights), max(weights))


def parse_status(production_status_value: str) -> str:
    """Maps WooCommerce's "Production-status" attribute to the schema's
    current/retired convention. Confirmed real values this session:
    "In Production" (current ball) and category-page evidence of a
    "Retired SWAG Bowling Balls" line (implies a "Discontinued" or similar
    value on those product pages, not directly confirmed by fetching one --
    matched by keyword rather than exact string for that reason)."""
    if not production_status_value:
        return None
    lowered = production_status_value.lower()
    if "discontinu" in lowered or "retired" in lowered:
        return "retired"
    if "production" in lowered:
        return "current"
    return None


def parse_resources(html: str, base_url: str) -> dict:
    """Captures the Info Sheet / Shelf Talker download links. Unlike
    Brunswick, the anchor text itself is generic ("Click HERE"), so this
    matches against the bold label text immediately preceding the link
    rather than the link's own text. Regex-based rather than BeautifulSoup
    here since the label isn't inside the same tag as the link (it's
    preceding sibling text) -- simpler to match against the raw HTML
    ordering directly.

    Note: both PDFs found on the one real product inspected this session
    are hosted on Dropbox share links, not SWAG's own CDN, and this
    session couldn't successfully fetch either one's actual content (the
    fetch tool available returned nothing for both, and no PDF bytes were
    ever inspected) -- so pdf_parser's Brunswick-specific layout
    assumptions are unverified against SWAG's info sheets and likely
    don't apply as-is even if fetching is solved. Not a blocker for this
    module: RG/DIFF/mass-bias-when-present already come from the HTML
    attribute table directly for SWAG, unlike Brunswick where the PDF was
    load-bearing for mass bias specifically.
    """
    resources = {}
    for label, pattern in [
        ("info_sheet_url", r"Info Sheet[^<]*</[a-zA-Z]+>\s*(?:-|–)\s*<a href=\"([^\"]+)\""),
        ("shelf_talker_url", r"Shelf Talker[^<]*</[a-zA-Z]+>\s*(?:-|–)\s*<a href=\"([^\"]+)\""),
    ]:
        match = re.search(pattern, html)
        if match:
            resources[label] = urljoin(base_url, match.group(1))
    return resources


def parse_images(soup: BeautifulSoup, base_url: str) -> list:
    """Main product image plus core-callout image, matched by position in
    the product gallery (first two <img> tags in the page, consistent
    with the real Fusion page's gallery order: ball photo, then core
    photo) rather than filename pattern -- SWAG's image filenames don't
    carry a reliable weight-range convention the way Brunswick's do."""
    images = []
    seen = set()
    for idx, img in enumerate(soup.find_all("img", src=True)):
        src = urljoin(base_url, img["src"])
        if src in seen:
            continue
        seen.add(src)
        alt = _clean(img.get("alt", ""))
        image_type = "main" if idx == 0 else ("core_callout" if idx == 1 else "other")
        images.append({"image_type": image_type, "source_url": src, "alt": alt})
        if idx >= 1:
            break  # only main + core image are reliably identifiable this way
    return images


def parse_description(soup: BeautifulSoup) -> str:
    """WooCommerce's short-description block, e.g. SWAG's Executioner Solid
    page has "The Executioner Solid is the strongest, most aggressive ball
    SWAG has ever built, engineered for the heavy fresh oil that shuts
    weaker equipment down...". Confirmed live via Claude in Chrome: sits in
    a container with class "product-short-description" -- WooCommerce's own
    standard class for this block (assigned by WooCommerce core's product
    template, same "stable WooCommerce convention, not site-specific theme
    markup" reasoning this module's docstring already gives for
    ATTRIBUTE_LABELS), so likely stable across other WooCommerce sites too,
    not just this one. Falls back to None for external/affiliate listings
    (see parse_product_page's external_product sentinel) -- those never
    reach this function since they return early."""
    el = soup.select_one(".product-short-description")
    if el is None:
        return None
    text = _clean(el.get_text(separator=" "))
    return text or None


def parse_product_page(html: str, url: str) -> dict:
    soup = BeautifulSoup(html, "lxml")

    h1 = soup.find("h1")
    name = _clean(h1.get_text()) if h1 else None

    table = _find_attributes_table(soup)
    attrs = parse_attributes_table(table) if table is not None else {}

    if not attrs:
        # Real finding from this deploy's first live smoke test: SWAG's
        # catalog includes WooCommerce "External/Affiliate Product"
        # listings -- confirmed via the product-type-external CSS class
        # and a total absence of the woocommerce-tabs/"Additional
        # information" section (checked against swag-apex-pearl-bowling-
        # ball's real page). These redirect to a different retailer
        # rather than being a real SWAG-hosted product page, so there's
        # no attribute data here at all, not just a differently-worded
        # Production-status field. Roughly a third of the real catalog
        # hit this on the first live run -- previously this silently
        # produced status=None, which crashed on the products.status
        # NOT NULL constraint (and pointlessly retried 3x into the DLQ,
        # since retrying never helps a permanently-external listing).
        # Returning this sentinel lets the caller skip cleanly instead.
        return {"url": url, "name": name, "external_product": True}

    coverstock = parse_coverstock(
        attrs.get("bowling ball coverstock type"),
        attrs.get("bowling ball cover name"),
    )

    rg = _to_float(attrs.get("radius of gyration: rg (15lb)"))
    diff = _to_float(attrs.get("differential: diff (15lb)"))
    mass_bias = parse_mass_bias(attrs.get("mass bias strength"))

    skus = []
    if rg is not None or diff is not None:
        skus = [{"weight_lbs": 15, "rg": rg, "differential": diff, "mass_bias": mass_bias}]

    return {
        "url": url,
        "name": name,
        "status": parse_status(attrs.get("production-status")),
        "color": attrs.get("colors"),
        "core_name": attrs.get("bowling ball core name"),
        "coverstock_name": attrs.get("bowling ball cover name"),
        "coverstock_material": coverstock["coverstock_material"],
        "coverstock_type": coverstock["coverstock_type"],
        "factory_finish": attrs.get("surface finish"),
        "weights_available": parse_weights_available(attrs.get("ball weight")),
        "release_date_raw": attrs.get("release date"),
        "release_date": parse_release_date(attrs.get("release date")),
        "performance_level_raw": attrs.get("ball performance level"),
        "skus": skus,
        "resources": parse_resources(html, url),
        "images": parse_images(soup, url),
        "description": parse_description(soup),
    }


# ---------------------------------------------------------------------
# Lambda handler + DB write. Same split/orchestration pattern as
# product_scraper/app.py -- see that module for the reasoning (pure
# parsing above, tested; mechanical DB/SQS below, deferred-imported).
#
# Now SQS-triggered from WooCommerceProductScrapeQueue (populated by
# WooCommerceUrlDiscoveryFunction) -- see template.yaml. Fans out to the
# SAME ImageProcessQueue/ImageProcessorFunction the Craft-CMS family uses
# (that function's job shape -- {product_image_id, source_url} -- and
# processing logic are both platform-agnostic, no reason to duplicate it
# per platform). Still no PdfParseQueue fan-out here -- SWAG doesn't need
# the PDF step for its core data (see module docstring), that part of the
# Craft-CMS chain genuinely doesn't apply to this platform.
# ---------------------------------------------------------------------

import json
import os


def get_db_connection():
    import boto3
    import psycopg2

    secret_arn = os.environ["DB_SECRET_ARN"]
    client = boto3.client("secretsmanager")
    secret = json.loads(client.get_secret_value(SecretId=secret_arn)["SecretString"])

    return psycopg2.connect(
        host=secret["host"],
        port=secret.get("port", 5432),
        dbname=secret["dbname"],
        user=secret["username"],
        password=secret["password"],
    )


def get_or_create_core_id(conn, brand_id: str, core_name, core_type=None):
    """Same helper as product_scraper.get_or_create_core_id -- duplicated
    rather than shared, same reasoning as publish_messages elsewhere in
    this project (each Lambda here is its own independent CodeUri package).
    SWAG's attrs don't expose a dedicated symmetric/asymmetric field (see
    this module's docstring), so core_type is always None here -- see
    migration 007 for why the cores table exists."""
    if not core_name:
        return None
    with conn.cursor() as cur:
        cur.execute(
            """
            insert into cores (brand_id, name, core_type)
            values (%s, %s, %s)
            on conflict (brand_id, name) do update set
                core_type = coalesce(cores.core_type, excluded.core_type)
            returning id
            """,
            (brand_id, core_name, core_type),
        )
        return cur.fetchone()[0]


def _normalize_coverstock_name(name):
    """Same helper as product_scraper._normalize_coverstock_name --
    duplicated rather than shared, same reasoning as get_or_create_core_id
    above. Strips TM/R/C marks and collapses whitespace before a
    coverstock_name is used as the coverstocks table's lookup/create key
    -- Al directly reported real duplicate coverstocks rows where the
    exact same formulation shows up with a trailing (TM)/(R)/(C) symbol
    on some scrapes/products and not others (a manufacturer page
    inconsistency, not a scraper bug). Only the coverstocks table's
    canonical name is normalized this way -- the raw, as-scraped text
    still goes into products.coverstock_name completely unchanged."""
    if not name:
        return None
    cleaned = re.sub(r"[™®©]", "", name)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned or None


def get_or_create_coverstock_id(conn, brand_id: str, coverstock_name, material=None, cs_type=None):
    """Same helper as product_scraper.get_or_create_coverstock_id --
    duplicated rather than shared, same reasoning as get_or_create_core_id
    above. See migration 008 for why this table exists, and
    _normalize_coverstock_name above for why the lookup key isn't just
    coverstock_name verbatim."""
    normalized_name = _normalize_coverstock_name(coverstock_name)
    if not normalized_name:
        return None
    with conn.cursor() as cur:
        cur.execute(
            """
            insert into coverstocks (brand_id, name, material, type)
            values (%s, %s, %s, %s)
            on conflict (brand_id, name) do update set
                material = coalesce(coverstocks.material, excluded.material),
                type = coalesce(coverstocks.type, excluded.type)
            returning id
            """,
            (brand_id, normalized_name, material, cs_type),
        )
        return cur.fetchone()[0]


def upsert_product(conn, brand_id: str, parsed: dict) -> dict:
    """Returns {"product_id": ..., "pending_image_jobs": [...]}, same shape
    as product_scraper.upsert_product -- the product_images insert now
    RETURNING id/stored_url (via "on conflict do update" rather than "do
    nothing", purely to make that RETURNING work on both new and
    pre-existing rows) so the handler can fan out image-process jobs
    without a second query."""
    weights_range = None
    if parsed["weights_available"]:
        low, high = parsed["weights_available"]
        weights_range = f"[{low},{high}]"

    core_id = get_or_create_core_id(conn, brand_id, parsed.get("core_name"))
    coverstock_id = get_or_create_coverstock_id(
        conn, brand_id, parsed.get("coverstock_name"),
        parsed.get("coverstock_material"), parsed.get("coverstock_type"),
    )

    # See product_scraper.upsert_product / migration 003 for the
    # discontinued_detected_at reasoning -- same logic here.
    with conn.cursor() as cur:
        cur.execute(
            """
            insert into products (
                brand_id, name, url, color, coverstock_material, coverstock_type,
                coverstock_name, factory_finish, weights_available, status, source_platform,
                release_date, description, discontinued_detected_at, core_id, coverstock_id
            )
            values (
                %s, %s, %s, %s, %s, %s, %s, %s, %s::int4range, %s, 'woocommerce', %s, %s,
                case when %s = 'retired' then now() else null end,
                %s, %s
            )
            on conflict (url) do update set
                name = excluded.name,
                color = excluded.color,
                coverstock_material = excluded.coverstock_material,
                coverstock_type = excluded.coverstock_type,
                coverstock_name = excluded.coverstock_name,
                factory_finish = excluded.factory_finish,
                weights_available = excluded.weights_available,
                status = excluded.status,
                release_date = coalesce(excluded.release_date, products.release_date),
                description = coalesce(excluded.description, products.description),
                core_id = coalesce(excluded.core_id, products.core_id),
                coverstock_id = coalesce(excluded.coverstock_id, products.coverstock_id),
                discontinued_detected_at = case
                    when excluded.status = 'retired' and products.status <> 'retired' then now()
                    when excluded.status = 'current' then null
                    else products.discontinued_detected_at
                end,
                updated_at = now()
            returning id
            """,
            (
                brand_id, parsed["name"], parsed["url"], parsed["color"],
                parsed["coverstock_material"], parsed["coverstock_type"],
                parsed["coverstock_name"], parsed["factory_finish"],
                weights_range, parsed["status"], parsed["release_date"], parsed["description"],
                parsed["status"], core_id, coverstock_id,
            ),
        )
        product_id = cur.fetchone()[0]

        for sku in parsed["skus"]:
            cur.execute(
                """
                insert into product_skus (product_id, weight_lbs, rg, differential, mass_bias, source)
                values (%s, %s, %s, %s, %s, 'html')
                on conflict (product_id, weight_lbs) do update set
                    rg = excluded.rg,
                    differential = excluded.differential,
                    mass_bias = coalesce(excluded.mass_bias, product_skus.mass_bias),
                    updated_at = now()
                """,
                (product_id, sku["weight_lbs"], sku["rg"], sku["differential"], sku["mass_bias"]),
            )

        pending_image_jobs = []
        for image in parsed["images"]:
            cur.execute(
                """
                insert into product_images (product_id, image_type, source_url)
                values (%s, %s, %s)
                on conflict (product_id, source_url) do update set image_type = excluded.image_type
                returning id, stored_url
                """,
                (product_id, image["image_type"], image["source_url"]),
            )
            image_id, stored_url = cur.fetchone()
            if stored_url is None:
                pending_image_jobs.append({"product_image_id": str(image_id), "source_url": image["source_url"]})

    conn.commit()
    return {"product_id": product_id, "pending_image_jobs": pending_image_jobs}


def build_image_process_messages(pending_image_jobs: list) -> list:
    return [json.dumps(job) for job in pending_image_jobs]


def publish_messages(sqs_client, queue_url: str, message_bodies: list) -> int:
    """Duplicated from product_scraper/app.py rather than shared -- see
    that module's docstring for why (each Lambda here is its own
    independent deployment package)."""
    sent = 0
    for i in range(0, len(message_bodies), 10):
        chunk = message_bodies[i:i + 10]
        entries = [{"Id": str(idx), "MessageBody": body} for idx, body in enumerate(chunk)]
        sqs_client.send_message_batch(QueueUrl=queue_url, Entries=entries)
        sent += len(chunk)
    return sent


def _extract_jobs(event: dict) -> list:
    """Same two-shape support (SQS batch or direct invoke) as
    product_scraper's _extract_jobs."""
    if "Records" in event:
        return [(json.loads(r["body"]), r["messageId"]) for r in event["Records"]]
    return [(event, None)]


def _process_one(job: dict, sqs_client) -> dict:
    url = job["url"]
    brand_id = job["brand_id"]

    logger.info("Scraping %s", url)
    html = fetch_page(url)
    parsed = parse_product_page(html, url)

    if parsed.get("external_product"):
        logger.warning(
            "Skipping %s -- WooCommerce external/affiliate product listing, "
            "no attribute data available to scrape (see parse_product_page's "
            "docstring)", url,
        )
        return {"product_id": None, "sku_count": 0, "image_jobs_published": 0, "skipped": "external_product"}

    conn = get_db_connection()
    try:
        result = upsert_product(conn, brand_id, parsed)
    finally:
        conn.close()

    product_id = result["product_id"]
    logger.info("Upserted product %s (%d SKUs)", product_id, len(parsed["skus"]))

    image_queue_url = os.environ.get("IMAGE_PROCESS_QUEUE_URL")
    image_jobs_published = 0
    if result["pending_image_jobs"] and image_queue_url:
        messages = build_image_process_messages(result["pending_image_jobs"])
        image_jobs_published = publish_messages(sqs_client, image_queue_url, messages)

    return {
        "product_id": str(product_id),
        "sku_count": len(parsed["skus"]),
        "image_jobs_published": image_jobs_published,
    }


def handler(event, context):
    """Handles both an SQS-triggered batch (WooCommerceProductScrapeQueue,
    populated by WooCommerceUrlDiscoveryFunction) and a direct/manual
    invocation with {"url": "...", "brand_id": "..."}, same
    batchItemFailures pattern as product_scraper's handler."""
    jobs = _extract_jobs(event)

    sqs_client = None
    if os.environ.get("IMAGE_PROCESS_QUEUE_URL"):
        import boto3

        sqs_client = boto3.client("sqs")

    results = []
    batch_item_failures = []
    for job, message_id in jobs:
        try:
            results.append(_process_one(job, sqs_client))
        except Exception:
            logger.exception("Failed to scrape/upsert job: %r", job)
            if message_id is not None:
                batch_item_failures.append({"itemIdentifier": message_id})
            else:
                raise

    response = {"statusCode": 200, "body": json.dumps({"results": results})}
    if "Records" in event:
        response["batchItemFailures"] = batch_item_failures
    return response
